### ISSUE TITLE
Use Variables For Matches

### ISSUE THREAD

**Issue by bpruitt-goddard** [bpruitt-goddard/vscode-mermaid-syntax-highlight#9]
Everything is declared in-line. Use some variables to get this going.

Example:

```json
"repository": {	
 "comments": {
    "match": "%%.*",
    "name": "comment"
  }
},
```

Then use it like this:

```json
"patterns": [
  {
    "include": "#comments"
  },
]
```

**Comment by bpruitt-goddard** [comment]
Currently, rules are written using the custom `regex` yaml type:

```yaml
- match: !regex |-
    (title)\s+ # title
    (\s*["\(\)$&%\^/#.,?!;:*+=<>\'\\\-\w\s]*) # text
  captures:
    '1':
      name: keyword.control.mermaid
    '2':
      name: string

```

YAML supports variables, but only for a single value, not for both the `match` and the `capture` that we would desire. To implement something like this, we would need to diverge from the spec and add a bit of custom work inside the `regex` type, which would make it harder for new folks to contribute:

```yaml
- match: !regex |-
    (title)\s+ # title
    &text_match
  captures:
    '1':
      name: keyword.control.mermaid
    '2':
      name: &text_capture

```


Instead, I think relying on the new test suite and trying to avoid duplication by using `begin`/`end` blocks in favor of multiple `match` blocks can help avoid this problem.

Closing this issue for now.
